#include <nan.h>
#include "tree_sitter/api.h"

// External declaration of the Tree-sitter grammar function (generated by tree-sitter)
extern "C" {
  TSLanguage *tree_sitter_mdsl();
}

// Wrapper function to expose the Tree-sitter grammar to Node.js
NAN_METHOD(New) {}

NAN_MODULE_INIT(Init) {
  v8::Local<v8::Object> exports = Nan::New<v8::Object>();
  Nan::Set(exports, Nan::New("name").ToLocalChecked(), Nan::New("mdsl").ToLocalChecked());
  Nan::Set(exports, Nan::New("version").ToLocalChecked(), Nan::New("0.1.0").ToLocalChecked());
  Nan::Set(exports, Nan::New("language").ToLocalChecked(),
           Nan::New<v8::External>(tree_sitter_mdsl()));
  target->Set(Nan::New("exports").ToLocalChecked(), exports);
}

NODE_MODULE(tree_sitter_mdsl_binding, Init)
