/* Automatically @generated by tree-sitter v0.25.5 (460118b4c82318b083b4d527c9c750426730f9c0) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_root = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_sequence = 4,
  anon_sym_selector = 5,
  anon_sym_parallel = 6,
  anon_sym_race = 7,
  anon_sym_all = 8,
  anon_sym_lotto = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_repeat = 13,
  anon_sym_retry = 14,
  anon_sym_flip = 15,
  anon_sym_succeed = 16,
  anon_sym_fail = 17,
  anon_sym_action = 18,
  anon_sym_condition = 19,
  anon_sym_wait = 20,
  anon_sym_branch = 21,
  anon_sym_null = 22,
  anon_sym_entry = 23,
  anon_sym_exit = 24,
  anon_sym_step = 25,
  anon_sym_LPAREN = 26,
  anon_sym_RPAREN = 27,
  anon_sym_while = 28,
  anon_sym_then = 29,
  anon_sym_until = 30,
  aux_sym_comment_token1 = 31,
  aux_sym_comment_token2 = 32,
  sym_identifier = 33,
  sym_number = 34,
  sym_string = 35,
  anon_sym_true = 36,
  anon_sym_false = 37,
  sym_source_file = 38,
  sym__definition = 39,
  sym_root_node = 40,
  sym_block = 41,
  sym__node = 42,
  sym_composite_node = 43,
  sym_lotto_node = 44,
  sym_decorator_node = 45,
  sym_leaf_node = 46,
  sym_node_args = 47,
  sym_arg_list = 48,
  sym__value = 49,
  sym_callbacks = 50,
  sym_guards = 51,
  sym_comment = 52,
  sym_boolean = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_block_repeat1 = 55,
  aux_sym_lotto_node_repeat1 = 56,
  aux_sym_arg_list_repeat1 = 57,
  aux_sym_callbacks_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_root] = "root",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_sequence] = "sequence",
  [anon_sym_selector] = "selector",
  [anon_sym_parallel] = "parallel",
  [anon_sym_race] = "race",
  [anon_sym_all] = "all",
  [anon_sym_lotto] = "lotto",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_repeat] = "repeat",
  [anon_sym_retry] = "retry",
  [anon_sym_flip] = "flip",
  [anon_sym_succeed] = "succeed",
  [anon_sym_fail] = "fail",
  [anon_sym_action] = "action",
  [anon_sym_condition] = "condition",
  [anon_sym_wait] = "wait",
  [anon_sym_branch] = "branch",
  [anon_sym_null] = "null",
  [anon_sym_entry] = "entry",
  [anon_sym_exit] = "exit",
  [anon_sym_step] = "step",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_while] = "while",
  [anon_sym_then] = "then",
  [anon_sym_until] = "until",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_root_node] = "root_node",
  [sym_block] = "block",
  [sym__node] = "_node",
  [sym_composite_node] = "composite_node",
  [sym_lotto_node] = "lotto_node",
  [sym_decorator_node] = "decorator_node",
  [sym_leaf_node] = "leaf_node",
  [sym_node_args] = "node_args",
  [sym_arg_list] = "arg_list",
  [sym__value] = "_value",
  [sym_callbacks] = "callbacks",
  [sym_guards] = "guards",
  [sym_comment] = "comment",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_lotto_node_repeat1] = "lotto_node_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
  [aux_sym_callbacks_repeat1] = "callbacks_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_root] = anon_sym_root,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_sequence] = anon_sym_sequence,
  [anon_sym_selector] = anon_sym_selector,
  [anon_sym_parallel] = anon_sym_parallel,
  [anon_sym_race] = anon_sym_race,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_lotto] = anon_sym_lotto,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_repeat] = anon_sym_repeat,
  [anon_sym_retry] = anon_sym_retry,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_succeed] = anon_sym_succeed,
  [anon_sym_fail] = anon_sym_fail,
  [anon_sym_action] = anon_sym_action,
  [anon_sym_condition] = anon_sym_condition,
  [anon_sym_wait] = anon_sym_wait,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_entry] = anon_sym_entry,
  [anon_sym_exit] = anon_sym_exit,
  [anon_sym_step] = anon_sym_step,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_until] = anon_sym_until,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_root_node] = sym_root_node,
  [sym_block] = sym_block,
  [sym__node] = sym__node,
  [sym_composite_node] = sym_composite_node,
  [sym_lotto_node] = sym_lotto_node,
  [sym_decorator_node] = sym_decorator_node,
  [sym_leaf_node] = sym_leaf_node,
  [sym_node_args] = sym_node_args,
  [sym_arg_list] = sym_arg_list,
  [sym__value] = sym__value,
  [sym_callbacks] = sym_callbacks,
  [sym_guards] = sym_guards,
  [sym_comment] = sym_comment,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_lotto_node_repeat1] = aux_sym_lotto_node_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
  [aux_sym_callbacks_repeat1] = aux_sym_callbacks_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_root] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sequence] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_selector] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_parallel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_race] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lotto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_retry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_succeed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fail] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_action] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_condition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_step] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_until] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_root_node] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_composite_node] = {
    .visible = true,
    .named = true,
  },
  [sym_lotto_node] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_node] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_node] = {
    .visible = true,
    .named = true,
  },
  [sym_node_args] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_callbacks] = {
    .visible = true,
    .named = true,
  },
  [sym_guards] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lotto_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callbacks_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(99);
      ADVANCE_MAP(
        '"', 2,
        '(', 126,
        ')', 127,
        ',', 110,
        '/', 3,
        '[', 109,
        ']', 111,
        'a', 13,
        'b', 77,
        'c', 66,
        'e', 61,
        'f', 6,
        'l', 67,
        'n', 92,
        'p', 10,
        'r', 7,
        's', 22,
        't', 37,
        'u', 63,
        'w', 11,
        '{', 101,
        '}', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(127);
      if (lookahead == 'f') ADVANCE(133);
      if (lookahead == 'n') ADVANCE(142);
      if (lookahead == 't') ADVANCE(139);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(146);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(131);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(132);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(43);
      if (lookahead == 'h') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(88);
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(87);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(115);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(147);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(149);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 36:
      if (lookahead == 'h') ADVANCE(120);
      END_STATE();
    case 37:
      if (lookahead == 'h') ADVANCE(31);
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(107);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(116);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(121);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(130);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(105);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(32);
      if (lookahead == 'q') ADVANCE(94);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(129);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(117);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(118);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(85);
      if (lookahead == 'x') ADVANCE(40);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(108);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(89);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(82);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 72:
      if (lookahead == 'p') ADVANCE(114);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(125);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(30);
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(104);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 80:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 92:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 93:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 94:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 95:
      if (lookahead == 'y') ADVANCE(123);
      END_STATE();
    case 96:
      if (lookahead == 'y') ADVANCE(113);
      END_STATE();
    case 97:
      if (lookahead == '{') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 98:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_root);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_sequence);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_selector);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_parallel);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_race);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_lotto);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_repeat);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_retry);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_succeed);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_fail);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_action);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_condition);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_wait);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_entry);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_exit);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_step);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_until);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(143);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 97},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 97},
  [119] = {.lex_state = 97},
  [120] = {.lex_state = 97},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_root] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_sequence] = ACTIONS(1),
    [anon_sym_selector] = ACTIONS(1),
    [anon_sym_parallel] = ACTIONS(1),
    [anon_sym_race] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_lotto] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_repeat] = ACTIONS(1),
    [anon_sym_retry] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_succeed] = ACTIONS(1),
    [anon_sym_fail] = ACTIONS(1),
    [anon_sym_action] = ACTIONS(1),
    [anon_sym_condition] = ACTIONS(1),
    [anon_sym_wait] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_entry] = ACTIONS(1),
    [anon_sym_exit] = ACTIONS(1),
    [anon_sym_step] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_until] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
    [aux_sym_comment_token2] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(111),
    [sym__definition] = STATE(66),
    [sym_root_node] = STATE(66),
    [sym_comment] = STATE(66),
    [aux_sym_source_file_repeat1] = STATE(66),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_root] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(7),
    [aux_sym_comment_token2] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_block] = STATE(42),
    [sym__node] = STATE(42),
    [sym_composite_node] = STATE(42),
    [sym_lotto_node] = STATE(42),
    [sym_decorator_node] = STATE(42),
    [sym_leaf_node] = STATE(42),
    [sym_node_args] = STATE(3),
    [sym_callbacks] = STATE(5),
    [sym_guards] = STATE(12),
    [sym_comment] = STATE(42),
    [aux_sym_callbacks_repeat1] = STATE(11),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_sequence] = ACTIONS(11),
    [anon_sym_selector] = ACTIONS(11),
    [anon_sym_parallel] = ACTIONS(11),
    [anon_sym_race] = ACTIONS(11),
    [anon_sym_all] = ACTIONS(11),
    [anon_sym_lotto] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_repeat] = ACTIONS(17),
    [anon_sym_retry] = ACTIONS(17),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_succeed] = ACTIONS(17),
    [anon_sym_fail] = ACTIONS(17),
    [anon_sym_action] = ACTIONS(19),
    [anon_sym_condition] = ACTIONS(19),
    [anon_sym_wait] = ACTIONS(21),
    [anon_sym_branch] = ACTIONS(23),
    [anon_sym_entry] = ACTIONS(25),
    [anon_sym_exit] = ACTIONS(25),
    [anon_sym_step] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_until] = ACTIONS(27),
    [aux_sym_comment_token1] = ACTIONS(7),
    [aux_sym_comment_token2] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_block] = STATE(37),
    [sym__node] = STATE(37),
    [sym_composite_node] = STATE(37),
    [sym_lotto_node] = STATE(37),
    [sym_decorator_node] = STATE(37),
    [sym_leaf_node] = STATE(37),
    [sym_callbacks] = STATE(4),
    [sym_guards] = STATE(13),
    [sym_comment] = STATE(37),
    [aux_sym_callbacks_repeat1] = STATE(11),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_sequence] = ACTIONS(11),
    [anon_sym_selector] = ACTIONS(11),
    [anon_sym_parallel] = ACTIONS(11),
    [anon_sym_race] = ACTIONS(11),
    [anon_sym_all] = ACTIONS(11),
    [anon_sym_lotto] = ACTIONS(13),
    [anon_sym_repeat] = ACTIONS(17),
    [anon_sym_retry] = ACTIONS(17),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_succeed] = ACTIONS(17),
    [anon_sym_fail] = ACTIONS(17),
    [anon_sym_action] = ACTIONS(19),
    [anon_sym_condition] = ACTIONS(19),
    [anon_sym_wait] = ACTIONS(21),
    [anon_sym_branch] = ACTIONS(23),
    [anon_sym_entry] = ACTIONS(25),
    [anon_sym_exit] = ACTIONS(25),
    [anon_sym_step] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_until] = ACTIONS(27),
    [aux_sym_comment_token1] = ACTIONS(7),
    [aux_sym_comment_token2] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    STATE(16), 1,
      sym_guards,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(56), 7,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
  [51] = 11,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    STATE(13), 1,
      sym_guards,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(37), 7,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
  [102] = 7,
    ACTIONS(31), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(22), 1,
      sym_callbacks,
    STATE(38), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(29), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [144] = 6,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(24), 1,
      sym_callbacks,
    STATE(48), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(33), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [183] = 6,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(23), 1,
      sym_callbacks,
    STATE(41), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(35), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [222] = 9,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(10), 7,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
      aux_sym_block_repeat1,
  [266] = 9,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(14), 7,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
      aux_sym_block_repeat1,
  [310] = 3,
    STATE(15), 1,
      aux_sym_callbacks_repeat1,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(41), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [342] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(37), 7,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
  [386] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(56), 7,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
  [430] = 9,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      anon_sym_lotto,
    ACTIONS(57), 1,
      anon_sym_wait,
    ACTIONS(60), 1,
      anon_sym_branch,
    ACTIONS(54), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(63), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(45), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(51), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(14), 7,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
      aux_sym_block_repeat1,
  [474] = 3,
    STATE(15), 1,
      aux_sym_callbacks_repeat1,
    ACTIONS(68), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(66), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [506] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(36), 7,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      sym_comment,
  [550] = 1,
    ACTIONS(71), 24,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [577] = 1,
    ACTIONS(73), 24,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [604] = 1,
    ACTIONS(75), 24,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [631] = 1,
    ACTIONS(77), 24,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [658] = 1,
    ACTIONS(79), 23,
      anon_sym_LBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [684] = 3,
    STATE(44), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(81), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [712] = 3,
    STATE(47), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(83), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [740] = 3,
    STATE(55), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(85), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [768] = 1,
    ACTIONS(87), 20,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [791] = 1,
    ACTIONS(89), 20,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [814] = 1,
    ACTIONS(91), 20,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [837] = 2,
    ACTIONS(95), 1,
      anon_sym_then,
    ACTIONS(93), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [862] = 2,
    ACTIONS(99), 1,
      anon_sym_then,
    ACTIONS(97), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [887] = 2,
    ACTIONS(103), 1,
      anon_sym_then,
    ACTIONS(101), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [912] = 2,
    ACTIONS(107), 1,
      anon_sym_then,
    ACTIONS(105), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [937] = 1,
    ACTIONS(105), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [959] = 1,
    ACTIONS(97), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [981] = 1,
    ACTIONS(109), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1003] = 1,
    ACTIONS(111), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1025] = 1,
    ACTIONS(113), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1046] = 1,
    ACTIONS(115), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1067] = 1,
    ACTIONS(81), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1088] = 1,
    ACTIONS(117), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1109] = 1,
    ACTIONS(119), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1130] = 1,
    ACTIONS(83), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1151] = 1,
    ACTIONS(121), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1172] = 1,
    ACTIONS(123), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1193] = 1,
    ACTIONS(125), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1214] = 1,
    ACTIONS(127), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1235] = 1,
    ACTIONS(129), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1256] = 1,
    ACTIONS(33), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1277] = 1,
    ACTIONS(85), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1298] = 1,
    ACTIONS(131), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1319] = 1,
    ACTIONS(133), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1340] = 1,
    ACTIONS(135), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1361] = 1,
    ACTIONS(137), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1382] = 1,
    ACTIONS(139), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1403] = 1,
    ACTIONS(141), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1424] = 1,
    ACTIONS(143), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1445] = 1,
    ACTIONS(145), 18,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1466] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(45), 1,
      sym_block,
    STATE(60), 1,
      sym_node_args,
    STATE(73), 1,
      sym_callbacks,
    STATE(94), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1497] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(53), 1,
      sym_block,
    STATE(70), 1,
      sym_callbacks,
    STATE(102), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1525] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(46), 1,
      sym_block,
    STATE(69), 1,
      sym_callbacks,
    STATE(95), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1550] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(49), 1,
      sym_block,
    STATE(72), 1,
      sym_callbacks,
    STATE(92), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1575] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      aux_sym_callbacks_repeat1,
    STATE(40), 1,
      sym_block,
    STATE(71), 1,
      sym_callbacks,
    STATE(98), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1600] = 5,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(149), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(153), 2,
      sym_number,
      sym_string,
    ACTIONS(155), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(77), 2,
      sym__value,
      sym_boolean,
  [1620] = 5,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    ACTIONS(155), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(157), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(161), 2,
      sym_number,
      sym_string,
    STATE(80), 2,
      sym__value,
      sym_boolean,
  [1640] = 5,
    STATE(117), 1,
      sym_arg_list,
    ACTIONS(155), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(163), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(165), 2,
      sym_number,
      sym_string,
    STATE(82), 2,
      sym__value,
      sym_boolean,
  [1660] = 5,
    STATE(115), 1,
      sym_arg_list,
    ACTIONS(155), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(163), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(165), 2,
      sym_number,
      sym_string,
    STATE(82), 2,
      sym__value,
      sym_boolean,
  [1680] = 4,
    ACTIONS(5), 1,
      anon_sym_root,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    STATE(68), 4,
      sym__definition,
      sym_root_node,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1697] = 4,
    ACTIONS(155), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(169), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(171), 2,
      sym_number,
      sym_string,
    STATE(78), 2,
      sym__value,
      sym_boolean,
  [1714] = 4,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 1,
      anon_sym_root,
    ACTIONS(178), 2,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
    STATE(68), 4,
      sym__definition,
      sym_root_node,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1731] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_block,
    STATE(101), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1745] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
    STATE(93), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1759] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
    STATE(95), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1773] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_block,
    STATE(90), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1787] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_block,
    STATE(92), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1801] = 3,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(184), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1812] = 1,
    ACTIONS(186), 4,
      ts_builtin_sym_end,
      anon_sym_root,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1819] = 1,
    ACTIONS(188), 4,
      ts_builtin_sym_end,
      anon_sym_root,
      aux_sym_comment_token1,
      aux_sym_comment_token2,
  [1826] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_arg_list_repeat1,
  [1836] = 1,
    ACTIONS(184), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1842] = 1,
    ACTIONS(194), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1848] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_arg_list_repeat1,
  [1858] = 3,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(75), 1,
      sym_block,
  [1868] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(85), 1,
      aux_sym_arg_list_repeat1,
  [1878] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_arg_list_repeat1,
  [1888] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_arg_list_repeat1,
  [1898] = 3,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
    STATE(74), 1,
      aux_sym_arg_list_repeat1,
  [1908] = 3,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym_lotto_node_repeat1,
  [1918] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      aux_sym_lotto_node_repeat1,
  [1928] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym_lotto_node_repeat1,
  [1938] = 2,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [1945] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_block,
  [1952] = 1,
    ACTIONS(223), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [1957] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_block,
  [1964] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_block,
  [1971] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_block,
  [1978] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_block,
  [1985] = 1,
    ACTIONS(225), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [1990] = 2,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
  [1997] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
  [2004] = 1,
    ACTIONS(231), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [2009] = 2,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RBRACK,
  [2016] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_block,
  [2023] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
  [2030] = 1,
    ACTIONS(211), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2035] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_block,
  [2042] = 1,
    ACTIONS(237), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [2047] = 1,
    ACTIONS(239), 1,
      anon_sym_RBRACK,
  [2051] = 1,
    ACTIONS(241), 1,
      sym_number,
  [2055] = 1,
    ACTIONS(243), 1,
      anon_sym_LBRACK,
  [2059] = 1,
    ACTIONS(245), 1,
      sym_number,
  [2063] = 1,
    ACTIONS(247), 1,
      sym_number,
  [2067] = 1,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [2071] = 1,
    ACTIONS(251), 1,
      sym_number,
  [2075] = 1,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
  [2079] = 1,
    ACTIONS(255), 1,
      anon_sym_LBRACK,
  [2083] = 1,
    ACTIONS(235), 1,
      anon_sym_RBRACK,
  [2087] = 1,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
  [2091] = 1,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
  [2095] = 1,
    ACTIONS(261), 1,
      sym_identifier,
  [2099] = 1,
    ACTIONS(263), 1,
      sym_identifier,
  [2103] = 1,
    ACTIONS(265), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 183,
  [SMALL_STATE(9)] = 222,
  [SMALL_STATE(10)] = 266,
  [SMALL_STATE(11)] = 310,
  [SMALL_STATE(12)] = 342,
  [SMALL_STATE(13)] = 386,
  [SMALL_STATE(14)] = 430,
  [SMALL_STATE(15)] = 474,
  [SMALL_STATE(16)] = 506,
  [SMALL_STATE(17)] = 550,
  [SMALL_STATE(18)] = 577,
  [SMALL_STATE(19)] = 604,
  [SMALL_STATE(20)] = 631,
  [SMALL_STATE(21)] = 658,
  [SMALL_STATE(22)] = 684,
  [SMALL_STATE(23)] = 712,
  [SMALL_STATE(24)] = 740,
  [SMALL_STATE(25)] = 768,
  [SMALL_STATE(26)] = 791,
  [SMALL_STATE(27)] = 814,
  [SMALL_STATE(28)] = 837,
  [SMALL_STATE(29)] = 862,
  [SMALL_STATE(30)] = 887,
  [SMALL_STATE(31)] = 912,
  [SMALL_STATE(32)] = 937,
  [SMALL_STATE(33)] = 959,
  [SMALL_STATE(34)] = 981,
  [SMALL_STATE(35)] = 1003,
  [SMALL_STATE(36)] = 1025,
  [SMALL_STATE(37)] = 1046,
  [SMALL_STATE(38)] = 1067,
  [SMALL_STATE(39)] = 1088,
  [SMALL_STATE(40)] = 1109,
  [SMALL_STATE(41)] = 1130,
  [SMALL_STATE(42)] = 1151,
  [SMALL_STATE(43)] = 1172,
  [SMALL_STATE(44)] = 1193,
  [SMALL_STATE(45)] = 1214,
  [SMALL_STATE(46)] = 1235,
  [SMALL_STATE(47)] = 1256,
  [SMALL_STATE(48)] = 1277,
  [SMALL_STATE(49)] = 1298,
  [SMALL_STATE(50)] = 1319,
  [SMALL_STATE(51)] = 1340,
  [SMALL_STATE(52)] = 1361,
  [SMALL_STATE(53)] = 1382,
  [SMALL_STATE(54)] = 1403,
  [SMALL_STATE(55)] = 1424,
  [SMALL_STATE(56)] = 1445,
  [SMALL_STATE(57)] = 1466,
  [SMALL_STATE(58)] = 1497,
  [SMALL_STATE(59)] = 1525,
  [SMALL_STATE(60)] = 1550,
  [SMALL_STATE(61)] = 1575,
  [SMALL_STATE(62)] = 1600,
  [SMALL_STATE(63)] = 1620,
  [SMALL_STATE(64)] = 1640,
  [SMALL_STATE(65)] = 1660,
  [SMALL_STATE(66)] = 1680,
  [SMALL_STATE(67)] = 1697,
  [SMALL_STATE(68)] = 1714,
  [SMALL_STATE(69)] = 1731,
  [SMALL_STATE(70)] = 1745,
  [SMALL_STATE(71)] = 1759,
  [SMALL_STATE(72)] = 1773,
  [SMALL_STATE(73)] = 1787,
  [SMALL_STATE(74)] = 1801,
  [SMALL_STATE(75)] = 1812,
  [SMALL_STATE(76)] = 1819,
  [SMALL_STATE(77)] = 1826,
  [SMALL_STATE(78)] = 1836,
  [SMALL_STATE(79)] = 1842,
  [SMALL_STATE(80)] = 1848,
  [SMALL_STATE(81)] = 1858,
  [SMALL_STATE(82)] = 1868,
  [SMALL_STATE(83)] = 1878,
  [SMALL_STATE(84)] = 1888,
  [SMALL_STATE(85)] = 1898,
  [SMALL_STATE(86)] = 1908,
  [SMALL_STATE(87)] = 1918,
  [SMALL_STATE(88)] = 1928,
  [SMALL_STATE(89)] = 1938,
  [SMALL_STATE(90)] = 1945,
  [SMALL_STATE(91)] = 1952,
  [SMALL_STATE(92)] = 1957,
  [SMALL_STATE(93)] = 1964,
  [SMALL_STATE(94)] = 1971,
  [SMALL_STATE(95)] = 1978,
  [SMALL_STATE(96)] = 1985,
  [SMALL_STATE(97)] = 1990,
  [SMALL_STATE(98)] = 1997,
  [SMALL_STATE(99)] = 2004,
  [SMALL_STATE(100)] = 2009,
  [SMALL_STATE(101)] = 2016,
  [SMALL_STATE(102)] = 2023,
  [SMALL_STATE(103)] = 2030,
  [SMALL_STATE(104)] = 2035,
  [SMALL_STATE(105)] = 2042,
  [SMALL_STATE(106)] = 2047,
  [SMALL_STATE(107)] = 2051,
  [SMALL_STATE(108)] = 2055,
  [SMALL_STATE(109)] = 2059,
  [SMALL_STATE(110)] = 2063,
  [SMALL_STATE(111)] = 2067,
  [SMALL_STATE(112)] = 2071,
  [SMALL_STATE(113)] = 2075,
  [SMALL_STATE(114)] = 2079,
  [SMALL_STATE(115)] = 2083,
  [SMALL_STATE(116)] = 2087,
  [SMALL_STATE(117)] = 2091,
  [SMALL_STATE(118)] = 2095,
  [SMALL_STATE(119)] = 2099,
  [SMALL_STATE(120)] = 2103,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 6, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callbacks, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 6, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 7, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_args, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 7, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 7, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 6, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 9, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 8, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 5, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 5, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 6, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 7, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 8, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 8, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_node, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_node, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lotto_node_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lotto_node_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [249] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 5,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
