/* Automatically @generated by tree-sitter v0.25.5 (460118b4c82318b083b4d527c9c750426730f9c0) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_root = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_sequence = 4,
  anon_sym_selector = 5,
  anon_sym_parallel = 6,
  anon_sym_race = 7,
  anon_sym_all = 8,
  anon_sym_lotto = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_repeat = 13,
  anon_sym_retry = 14,
  anon_sym_flip = 15,
  anon_sym_succeed = 16,
  anon_sym_fail = 17,
  anon_sym_action = 18,
  anon_sym_condition = 19,
  anon_sym_wait = 20,
  anon_sym_branch = 21,
  anon_sym_null = 22,
  anon_sym_entry = 23,
  anon_sym_exit = 24,
  anon_sym_step = 25,
  anon_sym_LPAREN = 26,
  anon_sym_RPAREN = 27,
  anon_sym_while = 28,
  anon_sym_then = 29,
  anon_sym_until = 30,
  sym_comment = 31,
  sym_identifier = 32,
  sym_number = 33,
  sym_string = 34,
  anon_sym_true = 35,
  anon_sym_false = 36,
  sym_source_file = 37,
  sym__definition = 38,
  sym_root_node = 39,
  sym_block = 40,
  sym__node = 41,
  sym_composite_node = 42,
  sym_lotto_node = 43,
  sym_decorator_node = 44,
  sym_leaf_node = 45,
  sym_node_args = 46,
  sym_arg_list = 47,
  sym__value = 48,
  sym_callbacks = 49,
  sym_guards = 50,
  sym_boolean = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_block_repeat1 = 53,
  aux_sym_lotto_node_repeat1 = 54,
  aux_sym_arg_list_repeat1 = 55,
  aux_sym_callbacks_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_root] = "root",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_sequence] = "sequence",
  [anon_sym_selector] = "selector",
  [anon_sym_parallel] = "parallel",
  [anon_sym_race] = "race",
  [anon_sym_all] = "all",
  [anon_sym_lotto] = "lotto",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_repeat] = "repeat",
  [anon_sym_retry] = "retry",
  [anon_sym_flip] = "flip",
  [anon_sym_succeed] = "succeed",
  [anon_sym_fail] = "fail",
  [anon_sym_action] = "action",
  [anon_sym_condition] = "condition",
  [anon_sym_wait] = "wait",
  [anon_sym_branch] = "branch",
  [anon_sym_null] = "null",
  [anon_sym_entry] = "entry",
  [anon_sym_exit] = "exit",
  [anon_sym_step] = "step",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_while] = "while",
  [anon_sym_then] = "then",
  [anon_sym_until] = "until",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_root_node] = "root_node",
  [sym_block] = "block",
  [sym__node] = "_node",
  [sym_composite_node] = "composite_node",
  [sym_lotto_node] = "lotto_node",
  [sym_decorator_node] = "decorator_node",
  [sym_leaf_node] = "leaf_node",
  [sym_node_args] = "node_args",
  [sym_arg_list] = "arg_list",
  [sym__value] = "_value",
  [sym_callbacks] = "callbacks",
  [sym_guards] = "guards",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_lotto_node_repeat1] = "lotto_node_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
  [aux_sym_callbacks_repeat1] = "callbacks_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_root] = anon_sym_root,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_sequence] = anon_sym_sequence,
  [anon_sym_selector] = anon_sym_selector,
  [anon_sym_parallel] = anon_sym_parallel,
  [anon_sym_race] = anon_sym_race,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_lotto] = anon_sym_lotto,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_repeat] = anon_sym_repeat,
  [anon_sym_retry] = anon_sym_retry,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_succeed] = anon_sym_succeed,
  [anon_sym_fail] = anon_sym_fail,
  [anon_sym_action] = anon_sym_action,
  [anon_sym_condition] = anon_sym_condition,
  [anon_sym_wait] = anon_sym_wait,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_entry] = anon_sym_entry,
  [anon_sym_exit] = anon_sym_exit,
  [anon_sym_step] = anon_sym_step,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_until] = anon_sym_until,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_root_node] = sym_root_node,
  [sym_block] = sym_block,
  [sym__node] = sym__node,
  [sym_composite_node] = sym_composite_node,
  [sym_lotto_node] = sym_lotto_node,
  [sym_decorator_node] = sym_decorator_node,
  [sym_leaf_node] = sym_leaf_node,
  [sym_node_args] = sym_node_args,
  [sym_arg_list] = sym_arg_list,
  [sym__value] = sym__value,
  [sym_callbacks] = sym_callbacks,
  [sym_guards] = sym_guards,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_lotto_node_repeat1] = aux_sym_lotto_node_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
  [aux_sym_callbacks_repeat1] = aux_sym_callbacks_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_root] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sequence] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_selector] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_parallel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_race] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lotto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_retry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_succeed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fail] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_action] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_condition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_step] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_until] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_root_node] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_composite_node] = {
    .visible = true,
    .named = true,
  },
  [sym_lotto_node] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_node] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_node] = {
    .visible = true,
    .named = true,
  },
  [sym_node_args] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_callbacks] = {
    .visible = true,
    .named = true,
  },
  [sym_guards] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lotto_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callbacks_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(99);
      ADVANCE_MAP(
        '"', 2,
        '(', 126,
        ')', 127,
        ',', 110,
        '/', 3,
        '[', 109,
        ']', 111,
        'a', 13,
        'b', 77,
        'c', 66,
        'e', 61,
        'f', 6,
        'l', 67,
        'n', 92,
        'p', 10,
        'r', 7,
        's', 22,
        't', 37,
        'u', 63,
        'w', 11,
        '{', 101,
        '}', 102,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(127);
      if (lookahead == 'f') ADVANCE(132);
      if (lookahead == 'n') ADVANCE(141);
      if (lookahead == 't') ADVANCE(138);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(145);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(131);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(43);
      if (lookahead == 'h') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(88);
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(87);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(115);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(106);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(148);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 36:
      if (lookahead == 'h') ADVANCE(120);
      END_STATE();
    case 37:
      if (lookahead == 'h') ADVANCE(31);
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'l') ADVANCE(80);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(107);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(116);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(121);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(130);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(105);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(32);
      if (lookahead == 'q') ADVANCE(94);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(129);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(117);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(118);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(85);
      if (lookahead == 'x') ADVANCE(40);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(108);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(89);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(82);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 72:
      if (lookahead == 'p') ADVANCE(114);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(125);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(30);
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(104);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 80:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(119);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 92:
      if (lookahead == 'u') ADVANCE(52);
      END_STATE();
    case 93:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 94:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 95:
      if (lookahead == 'y') ADVANCE(123);
      END_STATE();
    case 96:
      if (lookahead == 'y') ADVANCE(113);
      END_STATE();
    case 97:
      if (lookahead == '{') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(97);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 98:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_root);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_sequence);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_selector);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_parallel);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_race);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_lotto);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_repeat);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_retry);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_succeed);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_fail);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_action);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_condition);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_wait);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_entry);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_exit);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_step);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_until);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(147);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 97},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 97},
  [111] = {.lex_state = 97},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 97},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_root] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_sequence] = ACTIONS(1),
    [anon_sym_selector] = ACTIONS(1),
    [anon_sym_parallel] = ACTIONS(1),
    [anon_sym_race] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_lotto] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_repeat] = ACTIONS(1),
    [anon_sym_retry] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_succeed] = ACTIONS(1),
    [anon_sym_fail] = ACTIONS(1),
    [anon_sym_action] = ACTIONS(1),
    [anon_sym_condition] = ACTIONS(1),
    [anon_sym_wait] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_entry] = ACTIONS(1),
    [anon_sym_exit] = ACTIONS(1),
    [anon_sym_step] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_until] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(115),
    [sym__definition] = STATE(67),
    [sym_root_node] = STATE(67),
    [aux_sym_source_file_repeat1] = STATE(67),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_root] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_block] = STATE(35),
    [sym__node] = STATE(35),
    [sym_composite_node] = STATE(35),
    [sym_lotto_node] = STATE(35),
    [sym_decorator_node] = STATE(35),
    [sym_leaf_node] = STATE(35),
    [sym_node_args] = STATE(3),
    [sym_callbacks] = STATE(5),
    [sym_guards] = STATE(13),
    [aux_sym_callbacks_repeat1] = STATE(10),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_sequence] = ACTIONS(11),
    [anon_sym_selector] = ACTIONS(11),
    [anon_sym_parallel] = ACTIONS(11),
    [anon_sym_race] = ACTIONS(11),
    [anon_sym_all] = ACTIONS(11),
    [anon_sym_lotto] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_repeat] = ACTIONS(17),
    [anon_sym_retry] = ACTIONS(17),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_succeed] = ACTIONS(17),
    [anon_sym_fail] = ACTIONS(17),
    [anon_sym_action] = ACTIONS(19),
    [anon_sym_condition] = ACTIONS(19),
    [anon_sym_wait] = ACTIONS(21),
    [anon_sym_branch] = ACTIONS(23),
    [anon_sym_entry] = ACTIONS(25),
    [anon_sym_exit] = ACTIONS(25),
    [anon_sym_step] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_until] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym_block] = STATE(51),
    [sym__node] = STATE(51),
    [sym_composite_node] = STATE(51),
    [sym_lotto_node] = STATE(51),
    [sym_decorator_node] = STATE(51),
    [sym_leaf_node] = STATE(51),
    [sym_callbacks] = STATE(4),
    [sym_guards] = STATE(12),
    [aux_sym_callbacks_repeat1] = STATE(10),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_sequence] = ACTIONS(11),
    [anon_sym_selector] = ACTIONS(11),
    [anon_sym_parallel] = ACTIONS(11),
    [anon_sym_race] = ACTIONS(11),
    [anon_sym_all] = ACTIONS(11),
    [anon_sym_lotto] = ACTIONS(13),
    [anon_sym_repeat] = ACTIONS(17),
    [anon_sym_retry] = ACTIONS(17),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_succeed] = ACTIONS(17),
    [anon_sym_fail] = ACTIONS(17),
    [anon_sym_action] = ACTIONS(19),
    [anon_sym_condition] = ACTIONS(19),
    [anon_sym_wait] = ACTIONS(21),
    [anon_sym_branch] = ACTIONS(23),
    [anon_sym_entry] = ACTIONS(25),
    [anon_sym_exit] = ACTIONS(25),
    [anon_sym_step] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_until] = ACTIONS(27),
    [sym_comment] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(33), 1,
      sym_comment,
    STATE(15), 1,
      sym_guards,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(46), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [49] = 11,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      sym_comment,
    STATE(12), 1,
      sym_guards,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(51), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [98] = 7,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(22), 1,
      sym_callbacks,
    STATE(38), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(35), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [139] = 6,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(24), 1,
      sym_callbacks,
    STATE(39), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(39), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [177] = 6,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(23), 1,
      sym_callbacks,
    STATE(49), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(41), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [215] = 3,
    STATE(9), 1,
      aux_sym_callbacks_repeat1,
    ACTIONS(45), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(43), 20,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [246] = 3,
    STATE(9), 1,
      aux_sym_callbacks_repeat1,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(48), 20,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [277] = 9,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(52), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(17), 6,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      aux_sym_block_repeat1,
  [319] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(33), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(46), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [361] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(51), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [403] = 9,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      anon_sym_lotto,
    ACTIONS(68), 1,
      anon_sym_wait,
    ACTIONS(71), 1,
      anon_sym_branch,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(65), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(56), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(62), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(14), 6,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      aux_sym_block_repeat1,
  [445] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(77), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(37), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [487] = 1,
    ACTIONS(79), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [513] = 9,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(14), 6,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      aux_sym_block_repeat1,
  [555] = 1,
    ACTIONS(85), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [581] = 1,
    ACTIONS(87), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [607] = 1,
    ACTIONS(89), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [633] = 1,
    ACTIONS(91), 22,
      anon_sym_LBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [658] = 3,
    STATE(40), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(93), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [685] = 3,
    STATE(50), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(95), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [712] = 3,
    STATE(43), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(97), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [739] = 1,
    ACTIONS(99), 19,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [761] = 1,
    ACTIONS(101), 19,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [783] = 2,
    ACTIONS(105), 1,
      anon_sym_then,
    ACTIONS(103), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [807] = 2,
    ACTIONS(109), 1,
      anon_sym_then,
    ACTIONS(107), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [831] = 2,
    ACTIONS(113), 1,
      anon_sym_then,
    ACTIONS(111), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [855] = 2,
    ACTIONS(117), 1,
      anon_sym_then,
    ACTIONS(115), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [879] = 1,
    ACTIONS(119), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [900] = 1,
    ACTIONS(111), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [921] = 1,
    ACTIONS(115), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [942] = 1,
    ACTIONS(121), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [963] = 1,
    ACTIONS(123), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [983] = 1,
    ACTIONS(125), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1003] = 1,
    ACTIONS(127), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1023] = 1,
    ACTIONS(93), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1043] = 1,
    ACTIONS(97), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1063] = 1,
    ACTIONS(129), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1083] = 1,
    ACTIONS(131), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1103] = 1,
    ACTIONS(133), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1123] = 1,
    ACTIONS(41), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1143] = 1,
    ACTIONS(135), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1163] = 1,
    ACTIONS(137), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1183] = 1,
    ACTIONS(139), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1203] = 1,
    ACTIONS(141), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1223] = 1,
    ACTIONS(143), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1243] = 1,
    ACTIONS(95), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1263] = 1,
    ACTIONS(145), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1283] = 1,
    ACTIONS(147), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1303] = 1,
    ACTIONS(149), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1323] = 1,
    ACTIONS(151), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1343] = 1,
    ACTIONS(153), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1363] = 1,
    ACTIONS(155), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1383] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(36), 1,
      sym_block,
    STATE(60), 1,
      sym_node_args,
    STATE(72), 1,
      sym_callbacks,
    STATE(97), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1414] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(52), 1,
      sym_block,
    STATE(68), 1,
      sym_callbacks,
    STATE(91), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1442] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(55), 1,
      sym_block,
    STATE(69), 1,
      sym_callbacks,
    STATE(100), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1467] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(42), 1,
      sym_block,
    STATE(71), 1,
      sym_callbacks,
    STATE(93), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1492] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      aux_sym_callbacks_repeat1,
    STATE(41), 1,
      sym_block,
    STATE(70), 1,
      sym_callbacks,
    STATE(98), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1517] = 5,
    STATE(118), 1,
      sym_arg_list,
    ACTIONS(159), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(161), 2,
      sym_number,
      sym_string,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(80), 2,
      sym__value,
      sym_boolean,
  [1537] = 5,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(165), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(169), 2,
      sym_number,
      sym_string,
    STATE(81), 2,
      sym__value,
      sym_boolean,
  [1557] = 5,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(171), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(175), 2,
      sym_number,
      sym_string,
    STATE(82), 2,
      sym__value,
      sym_boolean,
  [1577] = 5,
    STATE(107), 1,
      sym_arg_list,
    ACTIONS(159), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(161), 2,
      sym_number,
      sym_string,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(80), 2,
      sym__value,
      sym_boolean,
  [1597] = 4,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(177), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(179), 2,
      sym_number,
      sym_string,
    STATE(74), 2,
      sym__value,
      sym_boolean,
  [1614] = 4,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(183), 1,
      anon_sym_root,
    ACTIONS(186), 1,
      sym_comment,
    STATE(66), 3,
      sym__definition,
      sym_root_node,
      aux_sym_source_file_repeat1,
  [1629] = 4,
    ACTIONS(5), 1,
      anon_sym_root,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 1,
      sym_comment,
    STATE(66), 3,
      sym__definition,
      sym_root_node,
      aux_sym_source_file_repeat1,
  [1644] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_block,
    STATE(99), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1658] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_block,
    STATE(93), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1672] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block,
    STATE(101), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1686] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_block,
    STATE(88), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1700] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
    STATE(98), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1714] = 3,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(196), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1725] = 1,
    ACTIONS(196), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1731] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      aux_sym_lotto_node_repeat1,
  [1741] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    STATE(73), 1,
      aux_sym_arg_list_repeat1,
  [1751] = 1,
    ACTIONS(206), 3,
      ts_builtin_sym_end,
      anon_sym_root,
      sym_comment,
  [1757] = 1,
    ACTIONS(208), 3,
      ts_builtin_sym_end,
      anon_sym_root,
      sym_comment,
  [1763] = 1,
    ACTIONS(210), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1769] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_arg_list_repeat1,
  [1779] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_arg_list_repeat1,
  [1789] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_arg_list_repeat1,
  [1799] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_arg_list_repeat1,
  [1809] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_arg_list_repeat1,
  [1819] = 3,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(222), 1,
      sym_identifier,
    STATE(77), 1,
      sym_block,
  [1829] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    STATE(75), 1,
      aux_sym_lotto_node_repeat1,
  [1839] = 3,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      aux_sym_lotto_node_repeat1,
  [1849] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_block,
  [1856] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_block,
  [1863] = 1,
    ACTIONS(231), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [1868] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_block,
  [1875] = 2,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
  [1882] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_block,
  [1889] = 1,
    ACTIONS(229), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1894] = 1,
    ACTIONS(237), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [1899] = 2,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
  [1906] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
  [1913] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block,
  [1920] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_block,
  [1927] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym_block,
  [1934] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_block,
  [1941] = 1,
    ACTIONS(243), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [1946] = 2,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_RBRACK,
  [1953] = 1,
    ACTIONS(249), 2,
      anon_sym_succeed,
      anon_sym_fail,
  [1958] = 1,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
  [1962] = 1,
    ACTIONS(253), 1,
      anon_sym_RBRACK,
  [1966] = 1,
    ACTIONS(255), 1,
      anon_sym_RBRACK,
  [1970] = 1,
    ACTIONS(257), 1,
      sym_number,
  [1974] = 1,
    ACTIONS(259), 1,
      anon_sym_LBRACK,
  [1978] = 1,
    ACTIONS(261), 1,
      sym_identifier,
  [1982] = 1,
    ACTIONS(263), 1,
      sym_identifier,
  [1986] = 1,
    ACTIONS(265), 1,
      anon_sym_LPAREN,
  [1990] = 1,
    ACTIONS(267), 1,
      sym_number,
  [1994] = 1,
    ACTIONS(269), 1,
      sym_identifier,
  [1998] = 1,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
  [2002] = 1,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
  [2006] = 1,
    ACTIONS(275), 1,
      sym_number,
  [2010] = 1,
    ACTIONS(247), 1,
      anon_sym_RBRACK,
  [2014] = 1,
    ACTIONS(277), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 98,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 177,
  [SMALL_STATE(9)] = 215,
  [SMALL_STATE(10)] = 246,
  [SMALL_STATE(11)] = 277,
  [SMALL_STATE(12)] = 319,
  [SMALL_STATE(13)] = 361,
  [SMALL_STATE(14)] = 403,
  [SMALL_STATE(15)] = 445,
  [SMALL_STATE(16)] = 487,
  [SMALL_STATE(17)] = 513,
  [SMALL_STATE(18)] = 555,
  [SMALL_STATE(19)] = 581,
  [SMALL_STATE(20)] = 607,
  [SMALL_STATE(21)] = 633,
  [SMALL_STATE(22)] = 658,
  [SMALL_STATE(23)] = 685,
  [SMALL_STATE(24)] = 712,
  [SMALL_STATE(25)] = 739,
  [SMALL_STATE(26)] = 761,
  [SMALL_STATE(27)] = 783,
  [SMALL_STATE(28)] = 807,
  [SMALL_STATE(29)] = 831,
  [SMALL_STATE(30)] = 855,
  [SMALL_STATE(31)] = 879,
  [SMALL_STATE(32)] = 900,
  [SMALL_STATE(33)] = 921,
  [SMALL_STATE(34)] = 942,
  [SMALL_STATE(35)] = 963,
  [SMALL_STATE(36)] = 983,
  [SMALL_STATE(37)] = 1003,
  [SMALL_STATE(38)] = 1023,
  [SMALL_STATE(39)] = 1043,
  [SMALL_STATE(40)] = 1063,
  [SMALL_STATE(41)] = 1083,
  [SMALL_STATE(42)] = 1103,
  [SMALL_STATE(43)] = 1123,
  [SMALL_STATE(44)] = 1143,
  [SMALL_STATE(45)] = 1163,
  [SMALL_STATE(46)] = 1183,
  [SMALL_STATE(47)] = 1203,
  [SMALL_STATE(48)] = 1223,
  [SMALL_STATE(49)] = 1243,
  [SMALL_STATE(50)] = 1263,
  [SMALL_STATE(51)] = 1283,
  [SMALL_STATE(52)] = 1303,
  [SMALL_STATE(53)] = 1323,
  [SMALL_STATE(54)] = 1343,
  [SMALL_STATE(55)] = 1363,
  [SMALL_STATE(56)] = 1383,
  [SMALL_STATE(57)] = 1414,
  [SMALL_STATE(58)] = 1442,
  [SMALL_STATE(59)] = 1467,
  [SMALL_STATE(60)] = 1492,
  [SMALL_STATE(61)] = 1517,
  [SMALL_STATE(62)] = 1537,
  [SMALL_STATE(63)] = 1557,
  [SMALL_STATE(64)] = 1577,
  [SMALL_STATE(65)] = 1597,
  [SMALL_STATE(66)] = 1614,
  [SMALL_STATE(67)] = 1629,
  [SMALL_STATE(68)] = 1644,
  [SMALL_STATE(69)] = 1658,
  [SMALL_STATE(70)] = 1672,
  [SMALL_STATE(71)] = 1686,
  [SMALL_STATE(72)] = 1700,
  [SMALL_STATE(73)] = 1714,
  [SMALL_STATE(74)] = 1725,
  [SMALL_STATE(75)] = 1731,
  [SMALL_STATE(76)] = 1741,
  [SMALL_STATE(77)] = 1751,
  [SMALL_STATE(78)] = 1757,
  [SMALL_STATE(79)] = 1763,
  [SMALL_STATE(80)] = 1769,
  [SMALL_STATE(81)] = 1779,
  [SMALL_STATE(82)] = 1789,
  [SMALL_STATE(83)] = 1799,
  [SMALL_STATE(84)] = 1809,
  [SMALL_STATE(85)] = 1819,
  [SMALL_STATE(86)] = 1829,
  [SMALL_STATE(87)] = 1839,
  [SMALL_STATE(88)] = 1849,
  [SMALL_STATE(89)] = 1856,
  [SMALL_STATE(90)] = 1863,
  [SMALL_STATE(91)] = 1868,
  [SMALL_STATE(92)] = 1875,
  [SMALL_STATE(93)] = 1882,
  [SMALL_STATE(94)] = 1889,
  [SMALL_STATE(95)] = 1894,
  [SMALL_STATE(96)] = 1899,
  [SMALL_STATE(97)] = 1906,
  [SMALL_STATE(98)] = 1913,
  [SMALL_STATE(99)] = 1920,
  [SMALL_STATE(100)] = 1927,
  [SMALL_STATE(101)] = 1934,
  [SMALL_STATE(102)] = 1941,
  [SMALL_STATE(103)] = 1946,
  [SMALL_STATE(104)] = 1953,
  [SMALL_STATE(105)] = 1958,
  [SMALL_STATE(106)] = 1962,
  [SMALL_STATE(107)] = 1966,
  [SMALL_STATE(108)] = 1970,
  [SMALL_STATE(109)] = 1974,
  [SMALL_STATE(110)] = 1978,
  [SMALL_STATE(111)] = 1982,
  [SMALL_STATE(112)] = 1986,
  [SMALL_STATE(113)] = 1990,
  [SMALL_STATE(114)] = 1994,
  [SMALL_STATE(115)] = 1998,
  [SMALL_STATE(116)] = 2002,
  [SMALL_STATE(117)] = 2006,
  [SMALL_STATE(118)] = 2010,
  [SMALL_STATE(119)] = 2014,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 6, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callbacks, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 6, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 7, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_args, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 7, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 5, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 6, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 7, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 9, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 8, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 5, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 6, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 7, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 8, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 8, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_node, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_node, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lotto_node_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lotto_node_repeat1, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [271] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 4,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
