/* Automatically @generated by tree-sitter v0.25.5 (460118b4c82318b083b4d527c9c750426730f9c0) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_root = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_sequence = 4,
  anon_sym_selector = 5,
  anon_sym_parallel = 6,
  anon_sym_race = 7,
  anon_sym_all = 8,
  anon_sym_lotto = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_repeat = 13,
  anon_sym_retry = 14,
  anon_sym_flip = 15,
  anon_sym_succeed = 16,
  anon_sym_fail = 17,
  anon_sym_action = 18,
  anon_sym_condition = 19,
  anon_sym_wait = 20,
  anon_sym_branch = 21,
  anon_sym_null = 22,
  anon_sym_entry = 23,
  anon_sym_exit = 24,
  anon_sym_step = 25,
  anon_sym_LPAREN = 26,
  anon_sym_RPAREN = 27,
  anon_sym_while = 28,
  anon_sym_until = 29,
  sym_comment = 30,
  sym_identifier = 31,
  sym_number = 32,
  sym_string = 33,
  anon_sym_true = 34,
  anon_sym_false = 35,
  sym_source_file = 36,
  sym__definition = 37,
  sym_root_node = 38,
  sym_block = 39,
  sym__node = 40,
  sym_composite_node = 41,
  sym_lotto_node = 42,
  sym_decorator_node = 43,
  sym_leaf_node = 44,
  sym_node_args = 45,
  sym_arg_list = 46,
  sym__value = 47,
  sym_callbacks = 48,
  sym_guards = 49,
  sym_boolean = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_block_repeat1 = 52,
  aux_sym_lotto_node_repeat1 = 53,
  aux_sym_arg_list_repeat1 = 54,
  aux_sym_callbacks_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_root] = "root",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_sequence] = "sequence",
  [anon_sym_selector] = "selector",
  [anon_sym_parallel] = "parallel",
  [anon_sym_race] = "race",
  [anon_sym_all] = "all",
  [anon_sym_lotto] = "lotto",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_repeat] = "repeat",
  [anon_sym_retry] = "retry",
  [anon_sym_flip] = "flip",
  [anon_sym_succeed] = "succeed",
  [anon_sym_fail] = "fail",
  [anon_sym_action] = "action",
  [anon_sym_condition] = "condition",
  [anon_sym_wait] = "wait",
  [anon_sym_branch] = "branch",
  [anon_sym_null] = "null",
  [anon_sym_entry] = "entry",
  [anon_sym_exit] = "exit",
  [anon_sym_step] = "step",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_while] = "while",
  [anon_sym_until] = "until",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_root_node] = "root_node",
  [sym_block] = "block",
  [sym__node] = "_node",
  [sym_composite_node] = "composite_node",
  [sym_lotto_node] = "lotto_node",
  [sym_decorator_node] = "decorator_node",
  [sym_leaf_node] = "leaf_node",
  [sym_node_args] = "node_args",
  [sym_arg_list] = "arg_list",
  [sym__value] = "_value",
  [sym_callbacks] = "callbacks",
  [sym_guards] = "guards",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_lotto_node_repeat1] = "lotto_node_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
  [aux_sym_callbacks_repeat1] = "callbacks_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_root] = anon_sym_root,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_sequence] = anon_sym_sequence,
  [anon_sym_selector] = anon_sym_selector,
  [anon_sym_parallel] = anon_sym_parallel,
  [anon_sym_race] = anon_sym_race,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_lotto] = anon_sym_lotto,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_repeat] = anon_sym_repeat,
  [anon_sym_retry] = anon_sym_retry,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_succeed] = anon_sym_succeed,
  [anon_sym_fail] = anon_sym_fail,
  [anon_sym_action] = anon_sym_action,
  [anon_sym_condition] = anon_sym_condition,
  [anon_sym_wait] = anon_sym_wait,
  [anon_sym_branch] = anon_sym_branch,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_entry] = anon_sym_entry,
  [anon_sym_exit] = anon_sym_exit,
  [anon_sym_step] = anon_sym_step,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_until] = anon_sym_until,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_root_node] = sym_root_node,
  [sym_block] = sym_block,
  [sym__node] = sym__node,
  [sym_composite_node] = sym_composite_node,
  [sym_lotto_node] = sym_lotto_node,
  [sym_decorator_node] = sym_decorator_node,
  [sym_leaf_node] = sym_leaf_node,
  [sym_node_args] = sym_node_args,
  [sym_arg_list] = sym_arg_list,
  [sym__value] = sym__value,
  [sym_callbacks] = sym_callbacks,
  [sym_guards] = sym_guards,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_lotto_node_repeat1] = aux_sym_lotto_node_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
  [aux_sym_callbacks_repeat1] = aux_sym_callbacks_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_root] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sequence] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_selector] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_parallel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_race] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lotto] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_retry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_succeed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fail] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_action] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_condition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_branch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entry] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_step] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_until] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_root_node] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_composite_node] = {
    .visible = true,
    .named = true,
  },
  [sym_lotto_node] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_node] = {
    .visible = true,
    .named = true,
  },
  [sym_leaf_node] = {
    .visible = true,
    .named = true,
  },
  [sym_node_args] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_callbacks] = {
    .visible = true,
    .named = true,
  },
  [sym_guards] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lotto_node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_callbacks_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(97);
      ADVANCE_MAP(
        '"', 2,
        '(', 124,
        ')', 125,
        ',', 108,
        '/', 3,
        '[', 107,
        ']', 109,
        'a', 13,
        'b', 75,
        'c', 63,
        'e', 58,
        'f', 6,
        'l', 64,
        'n', 90,
        'p', 10,
        'r', 7,
        's', 22,
        't', 74,
        'u', 60,
        'w', 11,
        '{', 99,
        '}', 100,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(125);
      if (lookahead == 'f') ADVANCE(129);
      if (lookahead == 'n') ADVANCE(138);
      if (lookahead == 't') ADVANCE(135);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(142);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(128);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(82);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(86);
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(85);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(113);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == 't') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(143);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(145);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(126);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(118);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(105);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(114);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(119);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(127);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(103);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead == 'q') ADVANCE(92);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(116);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(83);
      if (lookahead == 'x') ADVANCE(38);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(106);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(87);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(56);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(80);
      END_STATE();
    case 69:
      if (lookahead == 'p') ADVANCE(112);
      END_STATE();
    case 70:
      if (lookahead == 'p') ADVANCE(123);
      END_STATE();
    case 71:
      if (lookahead == 'p') ADVANCE(30);
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(102);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(91);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 78:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(122);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(98);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(117);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(110);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 90:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 91:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 92:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 93:
      if (lookahead == 'y') ADVANCE(121);
      END_STATE();
    case 94:
      if (lookahead == 'y') ADVANCE(111);
      END_STATE();
    case 95:
      if (lookahead == '{') ADVANCE(99);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 96:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_root);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_sequence);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_selector);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_parallel);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_race);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_lotto);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_repeat);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_retry);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_succeed);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_fail);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_action);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_condition);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_wait);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_branch);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_entry);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_exit);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_step);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_until);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(139);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 95},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 95},
  [94] = {.lex_state = 95},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 95},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_root] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_sequence] = ACTIONS(1),
    [anon_sym_selector] = ACTIONS(1),
    [anon_sym_parallel] = ACTIONS(1),
    [anon_sym_race] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_lotto] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_repeat] = ACTIONS(1),
    [anon_sym_retry] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_succeed] = ACTIONS(1),
    [anon_sym_fail] = ACTIONS(1),
    [anon_sym_action] = ACTIONS(1),
    [anon_sym_condition] = ACTIONS(1),
    [anon_sym_wait] = ACTIONS(1),
    [anon_sym_branch] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_entry] = ACTIONS(1),
    [anon_sym_exit] = ACTIONS(1),
    [anon_sym_step] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_until] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(98),
    [sym__definition] = STATE(58),
    [sym_root_node] = STATE(58),
    [aux_sym_source_file_repeat1] = STATE(58),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_root] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_block] = STATE(35),
    [sym__node] = STATE(35),
    [sym_composite_node] = STATE(35),
    [sym_lotto_node] = STATE(35),
    [sym_decorator_node] = STATE(35),
    [sym_leaf_node] = STATE(35),
    [sym_node_args] = STATE(3),
    [sym_callbacks] = STATE(4),
    [sym_guards] = STATE(12),
    [aux_sym_callbacks_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_sequence] = ACTIONS(11),
    [anon_sym_selector] = ACTIONS(11),
    [anon_sym_parallel] = ACTIONS(11),
    [anon_sym_race] = ACTIONS(11),
    [anon_sym_all] = ACTIONS(11),
    [anon_sym_lotto] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_repeat] = ACTIONS(17),
    [anon_sym_retry] = ACTIONS(17),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_succeed] = ACTIONS(17),
    [anon_sym_fail] = ACTIONS(17),
    [anon_sym_action] = ACTIONS(19),
    [anon_sym_condition] = ACTIONS(19),
    [anon_sym_wait] = ACTIONS(21),
    [anon_sym_branch] = ACTIONS(23),
    [anon_sym_entry] = ACTIONS(25),
    [anon_sym_exit] = ACTIONS(25),
    [anon_sym_step] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_until] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym_block] = STATE(38),
    [sym__node] = STATE(38),
    [sym_composite_node] = STATE(38),
    [sym_lotto_node] = STATE(38),
    [sym_decorator_node] = STATE(38),
    [sym_leaf_node] = STATE(38),
    [sym_callbacks] = STATE(5),
    [sym_guards] = STATE(16),
    [aux_sym_callbacks_repeat1] = STATE(8),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_sequence] = ACTIONS(11),
    [anon_sym_selector] = ACTIONS(11),
    [anon_sym_parallel] = ACTIONS(11),
    [anon_sym_race] = ACTIONS(11),
    [anon_sym_all] = ACTIONS(11),
    [anon_sym_lotto] = ACTIONS(13),
    [anon_sym_repeat] = ACTIONS(17),
    [anon_sym_retry] = ACTIONS(17),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_succeed] = ACTIONS(17),
    [anon_sym_fail] = ACTIONS(17),
    [anon_sym_action] = ACTIONS(19),
    [anon_sym_condition] = ACTIONS(19),
    [anon_sym_wait] = ACTIONS(21),
    [anon_sym_branch] = ACTIONS(23),
    [anon_sym_entry] = ACTIONS(25),
    [anon_sym_exit] = ACTIONS(25),
    [anon_sym_step] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_until] = ACTIONS(27),
    [sym_comment] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      sym_comment,
    STATE(16), 1,
      sym_guards,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(38), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [49] = 11,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(33), 1,
      sym_comment,
    STATE(14), 1,
      sym_guards,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(31), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [98] = 6,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(22), 1,
      sym_callbacks,
    STATE(39), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(35), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [136] = 6,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(21), 1,
      sym_callbacks,
    STATE(42), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(37), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [174] = 3,
    STATE(9), 1,
      aux_sym_callbacks_repeat1,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(39), 20,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [205] = 3,
    STATE(9), 1,
      aux_sym_callbacks_repeat1,
    ACTIONS(43), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
    ACTIONS(41), 20,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [236] = 1,
    ACTIONS(46), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [262] = 9,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 1,
      anon_sym_lotto,
    ACTIONS(62), 1,
      anon_sym_wait,
    ACTIONS(65), 1,
      anon_sym_branch,
    ACTIONS(68), 1,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(50), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(56), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(11), 6,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      aux_sym_block_repeat1,
  [304] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(38), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [346] = 9,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(11), 6,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      aux_sym_block_repeat1,
  [388] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(75), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(34), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [430] = 9,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(13), 6,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
      aux_sym_block_repeat1,
  [472] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_lotto,
    ACTIONS(21), 1,
      anon_sym_wait,
    ACTIONS(23), 1,
      anon_sym_branch,
    ACTIONS(33), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_action,
      anon_sym_condition,
    ACTIONS(11), 5,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
    ACTIONS(17), 5,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
    STATE(31), 6,
      sym_block,
      sym__node,
      sym_composite_node,
      sym_lotto_node,
      sym_decorator_node,
      sym_leaf_node,
  [514] = 1,
    ACTIONS(81), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [540] = 1,
    ACTIONS(83), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [566] = 1,
    ACTIONS(85), 23,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [592] = 1,
    ACTIONS(87), 22,
      anon_sym_LBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
      anon_sym_while,
      anon_sym_until,
      sym_comment,
  [617] = 3,
    STATE(47), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(89), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [644] = 3,
    STATE(43), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(91), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [671] = 1,
    ACTIONS(93), 19,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [693] = 1,
    ACTIONS(95), 19,
      ts_builtin_sym_end,
      anon_sym_root,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [715] = 1,
    ACTIONS(97), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [736] = 1,
    ACTIONS(99), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [757] = 1,
    ACTIONS(101), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [778] = 1,
    ACTIONS(103), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [799] = 1,
    ACTIONS(105), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [819] = 1,
    ACTIONS(107), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [839] = 1,
    ACTIONS(109), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [859] = 1,
    ACTIONS(111), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [879] = 1,
    ACTIONS(113), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [899] = 1,
    ACTIONS(115), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [919] = 1,
    ACTIONS(117), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [939] = 1,
    ACTIONS(119), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [959] = 1,
    ACTIONS(121), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [979] = 1,
    ACTIONS(123), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [999] = 1,
    ACTIONS(91), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1019] = 1,
    ACTIONS(125), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1039] = 1,
    ACTIONS(127), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1059] = 1,
    ACTIONS(89), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1079] = 1,
    ACTIONS(37), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1099] = 1,
    ACTIONS(129), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1119] = 1,
    ACTIONS(131), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1139] = 1,
    ACTIONS(133), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1159] = 1,
    ACTIONS(135), 17,
      anon_sym_RBRACE,
      anon_sym_sequence,
      anon_sym_selector,
      anon_sym_parallel,
      anon_sym_race,
      anon_sym_all,
      anon_sym_lotto,
      anon_sym_repeat,
      anon_sym_retry,
      anon_sym_flip,
      anon_sym_succeed,
      anon_sym_fail,
      anon_sym_action,
      anon_sym_condition,
      anon_sym_wait,
      anon_sym_branch,
      sym_comment,
  [1179] = 9,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(44), 1,
      sym_block,
    STATE(52), 1,
      sym_node_args,
    STATE(64), 1,
      sym_callbacks,
    STATE(91), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1210] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_LBRACK,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(30), 1,
      sym_block,
    STATE(60), 1,
      sym_callbacks,
    STATE(87), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1238] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(63), 1,
      sym_callbacks,
    STATE(84), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1263] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(37), 1,
      sym_block,
    STATE(61), 1,
      sym_callbacks,
    STATE(81), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1288] = 7,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      aux_sym_callbacks_repeat1,
    STATE(32), 1,
      sym_block,
    STATE(62), 1,
      sym_callbacks,
    STATE(85), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
    ACTIONS(25), 3,
      anon_sym_entry,
      anon_sym_exit,
      anon_sym_step,
  [1313] = 5,
    STATE(101), 1,
      sym_arg_list,
    ACTIONS(139), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(141), 2,
      sym_number,
      sym_string,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(71), 2,
      sym__value,
      sym_boolean,
  [1333] = 5,
    ACTIONS(147), 1,
      anon_sym_RPAREN,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(145), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(149), 2,
      sym_number,
      sym_string,
    STATE(73), 2,
      sym__value,
      sym_boolean,
  [1353] = 5,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(151), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(155), 2,
      sym_number,
      sym_string,
    STATE(72), 2,
      sym__value,
      sym_boolean,
  [1373] = 5,
    STATE(104), 1,
      sym_arg_list,
    ACTIONS(139), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(141), 2,
      sym_number,
      sym_string,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(71), 2,
      sym__value,
      sym_boolean,
  [1393] = 4,
    ACTIONS(143), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(157), 2,
      anon_sym_null,
      sym_identifier,
    ACTIONS(159), 2,
      sym_number,
      sym_string,
    STATE(69), 2,
      sym__value,
      sym_boolean,
  [1410] = 4,
    ACTIONS(5), 1,
      anon_sym_root,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 1,
      sym_comment,
    STATE(59), 3,
      sym__definition,
      sym_root_node,
      aux_sym_source_file_repeat1,
  [1425] = 4,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 1,
      anon_sym_root,
    ACTIONS(170), 1,
      sym_comment,
    STATE(59), 3,
      sym__definition,
      sym_root_node,
      aux_sym_source_file_repeat1,
  [1440] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
    STATE(88), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1454] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_block,
    STATE(84), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1468] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
    STATE(82), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1482] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
    STATE(90), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1496] = 4,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_block,
    STATE(85), 1,
      sym_guards,
    ACTIONS(27), 2,
      anon_sym_while,
      anon_sym_until,
  [1510] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
    ACTIONS(176), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1521] = 3,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_lotto_node_repeat1,
  [1531] = 1,
    ACTIONS(183), 3,
      ts_builtin_sym_end,
      anon_sym_root,
      sym_comment,
  [1537] = 3,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(78), 1,
      sym_block,
  [1547] = 1,
    ACTIONS(176), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1553] = 1,
    ACTIONS(187), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1559] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      aux_sym_arg_list_repeat1,
  [1569] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_arg_list_repeat1,
  [1579] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_arg_list_repeat1,
  [1589] = 3,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_lotto_node_repeat1,
  [1599] = 3,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(74), 1,
      aux_sym_lotto_node_repeat1,
  [1609] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
  [1619] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
  [1629] = 1,
    ACTIONS(207), 3,
      ts_builtin_sym_end,
      anon_sym_root,
      sym_comment,
  [1635] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      aux_sym_arg_list_repeat1,
  [1645] = 2,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
  [1652] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_block,
  [1659] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_block,
  [1666] = 2,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
  [1673] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_block,
  [1680] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
  [1687] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_block,
  [1694] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
  [1701] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_block,
  [1708] = 1,
    ACTIONS(181), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1713] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_block,
  [1720] = 2,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_block,
  [1727] = 1,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
  [1731] = 1,
    ACTIONS(221), 1,
      sym_identifier,
  [1735] = 1,
    ACTIONS(223), 1,
      sym_identifier,
  [1739] = 1,
    ACTIONS(225), 1,
      anon_sym_LBRACK,
  [1743] = 1,
    ACTIONS(227), 1,
      sym_identifier,
  [1747] = 1,
    ACTIONS(229), 1,
      sym_number,
  [1751] = 1,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
  [1755] = 1,
    ACTIONS(233), 1,
      anon_sym_LPAREN,
  [1759] = 1,
    ACTIONS(235), 1,
      anon_sym_LBRACK,
  [1763] = 1,
    ACTIONS(237), 1,
      anon_sym_RBRACK,
  [1767] = 1,
    ACTIONS(239), 1,
      sym_number,
  [1771] = 1,
    ACTIONS(241), 1,
      sym_number,
  [1775] = 1,
    ACTIONS(243), 1,
      anon_sym_RBRACK,
  [1779] = 1,
    ACTIONS(245), 1,
      anon_sym_COMMA,
  [1783] = 1,
    ACTIONS(247), 1,
      anon_sym_LBRACK,
  [1787] = 1,
    ACTIONS(249), 1,
      anon_sym_LPAREN,
  [1791] = 1,
    ACTIONS(251), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 49,
  [SMALL_STATE(6)] = 98,
  [SMALL_STATE(7)] = 136,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 205,
  [SMALL_STATE(10)] = 236,
  [SMALL_STATE(11)] = 262,
  [SMALL_STATE(12)] = 304,
  [SMALL_STATE(13)] = 346,
  [SMALL_STATE(14)] = 388,
  [SMALL_STATE(15)] = 430,
  [SMALL_STATE(16)] = 472,
  [SMALL_STATE(17)] = 514,
  [SMALL_STATE(18)] = 540,
  [SMALL_STATE(19)] = 566,
  [SMALL_STATE(20)] = 592,
  [SMALL_STATE(21)] = 617,
  [SMALL_STATE(22)] = 644,
  [SMALL_STATE(23)] = 671,
  [SMALL_STATE(24)] = 693,
  [SMALL_STATE(25)] = 715,
  [SMALL_STATE(26)] = 736,
  [SMALL_STATE(27)] = 757,
  [SMALL_STATE(28)] = 778,
  [SMALL_STATE(29)] = 799,
  [SMALL_STATE(30)] = 819,
  [SMALL_STATE(31)] = 839,
  [SMALL_STATE(32)] = 859,
  [SMALL_STATE(33)] = 879,
  [SMALL_STATE(34)] = 899,
  [SMALL_STATE(35)] = 919,
  [SMALL_STATE(36)] = 939,
  [SMALL_STATE(37)] = 959,
  [SMALL_STATE(38)] = 979,
  [SMALL_STATE(39)] = 999,
  [SMALL_STATE(40)] = 1019,
  [SMALL_STATE(41)] = 1039,
  [SMALL_STATE(42)] = 1059,
  [SMALL_STATE(43)] = 1079,
  [SMALL_STATE(44)] = 1099,
  [SMALL_STATE(45)] = 1119,
  [SMALL_STATE(46)] = 1139,
  [SMALL_STATE(47)] = 1159,
  [SMALL_STATE(48)] = 1179,
  [SMALL_STATE(49)] = 1210,
  [SMALL_STATE(50)] = 1238,
  [SMALL_STATE(51)] = 1263,
  [SMALL_STATE(52)] = 1288,
  [SMALL_STATE(53)] = 1313,
  [SMALL_STATE(54)] = 1333,
  [SMALL_STATE(55)] = 1353,
  [SMALL_STATE(56)] = 1373,
  [SMALL_STATE(57)] = 1393,
  [SMALL_STATE(58)] = 1410,
  [SMALL_STATE(59)] = 1425,
  [SMALL_STATE(60)] = 1440,
  [SMALL_STATE(61)] = 1454,
  [SMALL_STATE(62)] = 1468,
  [SMALL_STATE(63)] = 1482,
  [SMALL_STATE(64)] = 1496,
  [SMALL_STATE(65)] = 1510,
  [SMALL_STATE(66)] = 1521,
  [SMALL_STATE(67)] = 1531,
  [SMALL_STATE(68)] = 1537,
  [SMALL_STATE(69)] = 1547,
  [SMALL_STATE(70)] = 1553,
  [SMALL_STATE(71)] = 1559,
  [SMALL_STATE(72)] = 1569,
  [SMALL_STATE(73)] = 1579,
  [SMALL_STATE(74)] = 1589,
  [SMALL_STATE(75)] = 1599,
  [SMALL_STATE(76)] = 1609,
  [SMALL_STATE(77)] = 1619,
  [SMALL_STATE(78)] = 1629,
  [SMALL_STATE(79)] = 1635,
  [SMALL_STATE(80)] = 1645,
  [SMALL_STATE(81)] = 1652,
  [SMALL_STATE(82)] = 1659,
  [SMALL_STATE(83)] = 1666,
  [SMALL_STATE(84)] = 1673,
  [SMALL_STATE(85)] = 1680,
  [SMALL_STATE(86)] = 1687,
  [SMALL_STATE(87)] = 1694,
  [SMALL_STATE(88)] = 1701,
  [SMALL_STATE(89)] = 1708,
  [SMALL_STATE(90)] = 1713,
  [SMALL_STATE(91)] = 1720,
  [SMALL_STATE(92)] = 1727,
  [SMALL_STATE(93)] = 1731,
  [SMALL_STATE(94)] = 1735,
  [SMALL_STATE(95)] = 1739,
  [SMALL_STATE(96)] = 1743,
  [SMALL_STATE(97)] = 1747,
  [SMALL_STATE(98)] = 1751,
  [SMALL_STATE(99)] = 1755,
  [SMALL_STATE(100)] = 1759,
  [SMALL_STATE(101)] = 1763,
  [SMALL_STATE(102)] = 1767,
  [SMALL_STATE(103)] = 1771,
  [SMALL_STATE(104)] = 1775,
  [SMALL_STATE(105)] = 1779,
  [SMALL_STATE(106)] = 1783,
  [SMALL_STATE(107)] = 1787,
  [SMALL_STATE(108)] = 1791,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 6, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_callbacks, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 6, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_callbacks_repeat1, 7, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_args, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 7, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 7, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 6, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guards, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 6, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 5, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 5, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorator_node, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 8, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_composite_node, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lotto_node, 7, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leaf_node, 8, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lotto_node_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lotto_node_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_node, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_node, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [231] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
